import { doc, getDoc, deleteDoc } from "firebase/firestore";
import { ref, deleteObject } from "firebase/storage";
import { db, storage } from "@/lib/firebase";

export default async function handler(req, res) {
  if (req.method !== "DELETE") {
    return res
      .status(405)
      .json({ error: `Method '${req.method}' Not Allowed` });
  }

  try {
    const { blogId } = req.body;

    if (!blogId) {
      return res.status(400).json({ error: "Missing blogId in request body." });
    }

    const blogRef = doc(db, "blogs", blogId);
    const blogSnap = await getDoc(blogRef);

    if (!blogSnap.exists()) {
      return res.status(404).json({ error: "Blog not found." });
    }

    const blogData = blogSnap.data();

    // First, delete the image from Firebase Storage if it exists
    if (blogData.imageUrl) {
      try {
        // Derive the storage path from the imageUrl
        // Assuming the imageUrl was generated by getDownloadURL and includes the storage bucket structure
        // Extract the path after "/o/" and until "?" (for blog images it would be "blogs/<filename>")
        const decodedUrl = decodeURIComponent(blogData.imageUrl);
        const matches = decodedUrl.match(/\/o\/(.+)\?/);
        if (matches && matches[1]) {
          const imagePath = matches[1];
          const imageRef = ref(storage, imagePath);
          await deleteObject(imageRef);
        }
      } catch (imgErr) {
        // If image deletion fails, still try to delete the blog, but log this error
        console.error("Failed to delete image from storage:", imgErr.message);
      }
    }

    // Then, delete the blog document from Firestore
    await deleteDoc(blogRef);

    res.status(200).json({ message: "Blog and image deleted successfully!" });
  } catch (error) {
    res.status(500).json({ error: error.message || "Failed to delete blog." });
  }
}